name: Compilar EXE

on: [push] # Compila toda vez que você salvar o código

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Instalar Bibliotecas
      run: |
        pip install pyinstaller customtkinter
    - name: Gerar Executável
      run: |
        pyinstaller --noconsole --onefile --name "BuscaPreco_LJ27" main.py
    - name: Salvar Resultado
      uses: actions/upload-artifact@v3
      with:
        name: Executavel_LJ27
        path: dist/BuscaPreco_LJ27.exe
