name: Compilar EXE

on: 
  workflow_dispatch: 
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout do Código
      uses: actions/checkout@v4 # Atualizado para v4
    
    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Instalar Dependencias
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller customtkinter
        
    - name: Compilar com PyInstaller
      run: |
        pyinstaller --noconsole --onefile --name "BuscaPreco_LJ27" main.py
        
    - name: Salvar Executavel
      uses: actions/upload-artifact@v4 # Versão Corrigida para v4
      with:
        name: BuscaPreco_LJ27_EXE
        path: dist/BuscaPreco_LJ27.exe
